//
export const GET_MEAL_DETAILS_LOADING = "GET_MEAL_DETAILS_LOADING";
export const GET_MEAL_DETAILS_SUCCESS = "GET_MEAL_DETAILS_SUCCESS";
export const GET_MEAL_DETAILS_ERROR = "GET_MEAL_DETAILS_ERROR";
//
export const ADD_MEAL_DETAILS_LOADING = "ADD_MEAL_DETAILS_LOADING";
export const ADD_MEAL_DETAILS_SUCCESS = "ADD_MEAL_DETAILS_SUCCESS";
export const ADD_MEAL_DETAILS_ERROR = "ADD_MEAL_DETAILS_ERROR";
//
export const UPDATE_MEAL_DETAILS_LOADING = "UPDATE_MEAL_DETAILS_LOADING";
export const UPDATE_MEAL_DETAILS_SUCCESS = "UPDATE_MEAL_DETAILS_SUCCESS";
export const UPDATE_MEAL_DETAILS_ERROR = "UPDATE_MEAL_DETAILS_ERROR";
//
export const DELETE_MEAL_DETAILS_LOADING = "DELETE_MEAL_DETAILS_LOADING";
export const DELETE_MEAL_DETAILS_SUCCESS = "DELETE_MEAL_DETAILS_SUCCESS";
export const DELETE_MEAL_DETAILS_ERROR = "DELETE_MEAL_DETAILS_ERROR";
