//
export const GET_DOG_DETAILS_LOADING = "GET_DOG_DETAILS_LOADING";
export const GET_DOG_DETAILS_SUCCESS = "GET_DOG_DETAILS_SUCCESS";
export const GET_DOG_DETAILS_ERROR = "GET_DOG_DETAILS_ERROR";
//
export const ADD_DOG_DETAILS_LOADING = "ADD_DOG_DETAILS_LOADING";
export const ADD_DOG_DETAILS_SUCCESS = "ADD_DOG_DETAILS_SUCCESS";
export const ADD_DOG_DETAILS_ERROR = "ADD_DOG_DETAILS_ERROR";
//
export const UPDATE_DOG_DETAILS_LOADING = "UPDATE_DOG_DETAILS_LOADING";
export const UPDATE_DOG_DETAILS_SUCCESS = "UPDATE_DOG_DETAILS_SUCCESS";
export const UPDATE_DOG_DETAILS_ERROR = "UPDATE_DOG_DETAILS_ERROR";
//
export const DELETE_DOG_DETAILS_LOADING = "DELETE_DOG_DETAILS_LOADING";
export const DELETE_DOG_DETAILS_SUCCESS = "DELETE_DOG_DETAILS_SUCCESS";
export const DELETE_DOG_DETAILS_ERROR = "DELETE_DOG_DETAILS_ERROR";
